# Generated by Django 5.0.6 on 2024-07-07 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('nombre_supervisor', models.CharField(max_length=10)),
                ('apellido_supervisor', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('EPRG', 'EPRG'), ('PRD', 'PRD'), ('PRA', 'PRA')], default='PRD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('nombre_usuario', models.CharField(default='Desconocido', max_length=10)),
                ('apellido_usuario', models.CharField(default='Desconocido', max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('EPRG', 'EPRG'), ('PRD', 'PRD'), ('PRA', 'PRA')], default='PRD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=78)),
                ('litros', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=300)),
                ('hora', models.CharField(max_length=100)),
                ('operador', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
